name: 'Verify'

on:
  push:

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Format
        run: cargo fmt --check
      - name: Test
        run: cargo test
